version: '3.4'

services:
  # a fully loaded development environment to test new code
  dev:
    &dev
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code

  # run tests
  test:
    <<: *dev
    command: pytest -v --cov=. --cov-report term-missing --cov-fail-under 90

  # run linters
  lint:
    <<: *dev
    entrypoint: ./docker/lint.sh
