[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
line_length = 120
include_trailing_comma = true

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.setuptools_scm]
